### ISSUE TITLE
Wrong link on atmosphere

### ISSUE THREAD

**Issue by jhuenges** [jchristman/meteor-collection-scroller#1]
The link on atmosphere is: https://github.com/suntzuII/meteor-collection-scroller/

**Comment by jchristman** [comment]
Thank you. I just changed my username a few weeks ago and am still getting used to it... If you are wanting to check out the library's functionality, documentation is still scarce because I am still writing it, but you can check out the example in the repo to test it out. The basic functionality works and I will be updating this over the next few days as I expand the library.

**Comment by jhuenges** [comment]
:+1:
